# Generated by Django 3.0.3 on 2020-03-02 21:09

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('data_file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/data'), upload_to='')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
