# Generated by Django 3.0.3 on 2020-03-02 22:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datafile',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RemoveField(
            model_name='datafile',
            name='data_file',
        ),
        migrations.RemoveField(
            model_name='datafile',
            name='name',
        ),
        migrations.AddField(
            model_name='datafile',
            name='datafile',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
