# Generated by Django 3.0.3 on 2020-03-02 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200302_1707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datafile',
            old_name='datafile',
            new_name='file',
        ),
    ]
